### ISSUE TITLE
Implement Lua/C function to merge net.box results 

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/shard#14]
Implement Lua/C function which takes merges array of ibufs with [raw net.box MessagePack results](https://github.com/tarantool/tarantool/issues/2195 ) and merges it into array of tuples:

```
shard({ array of ibufs }, iterator_type, offset, limit, key_def) => { tuple, tuple, ...}
```

This feature is needed to avoid creation of the huge number of Lua objects in #5. 

Blocked by https://github.com/tarantool/tarantool/issues/2195, https://github.com/tarantool/tarantool/issues/1878, https://github.com/tarantool/tarantool/issues/2225 and #15

**Comment by GeorgyKirichenko** [comment]
Done
