### ISSUE TITLE
Automated testing

### ISSUE THREAD

**Issue by kostja** [tarantool/shard#4]
Automate sharding tests with test-run

**Comment by Sulverus** [comment]
1. Added test-run submodule
2. Writed tests for single shard and multiple nodes with redundancy
3. Found and fixed 2 bugs: 
   * single_call fails with redundancy after last patches
   * check_operations fails if operation does not exists

**Comment by Sulverus** [comment]
Tests implementation done.
After review todo list:
1. rename suites `lua` to `redundancy`
2. remove all `sleep()` in tests (implement function based on `get_heartbeat` - to check that all shards is ready)

**Comment by Sulverus** [comment]
Done.
tests updated for new shard function: https://github.com/tarantool/shard/commit/ca62d6d39867a64eff557e89f9e31fa2b907a875
