### ISSUE TITLE
Batch 2-phase (q_*) operations

### ISSUE THREAD

**Issue by kostja** [tarantool/shard#7]
Implement q_begin(), which starts a batch operation, and q_end() which waits fro it to finish. All batch tasks can be run concurrently.

**Comment by Sulverus** [comment]
queue_request function modified: it's possible use q_* operations with batching. Example:
```lua
q = shard.q_begin()
shard.demo.q_auto_increment(7, {'batch1'})
shard.demo.q_auto_increment(8, {'batch2'})
shard.demo.q_auto_increment(9, {'batch3'})
shard.q_end(q)
```
All operations in batch executed in transaction. Please review

**Comment by Sulverus** [comment]
Api updated:
```lua
batch = shard.q_begin()
batch.demo:q_auto_increment(7, {'batch1'})
batch.demo:q_auto_increment(8, {'batch2'})
batch.demo:q_auto_increment(9, {'batch3'})
batch:q_end()
```

**Comment by Sulverus** [comment]
Updated with https://github.com/tarantool/shard/commit/a3b52512243ff0bdb091ce2310f06a5890d6ce32
Tested with tx
