### ISSUE TITLE
Debian package build for ubuntu:bionic fails

### ISSUE THREAD

**Issue by SudoBobo** [tarantool/shard#77]
https://travis-ci.org/tarantool/shard/jobs/391680760

**Comment by Totktonada** [comment]
Set PACKAGECLOUD_REPO to 1_9. See https://github.com/tarantool/avro-schema/issues/96

**Comment by Totktonada** [comment]
Updated to 1_10, because there are no builds for recent Fedora (>= 28) in our 1_9 repository.

**Comment by Totktonada** [comment]
Deploy targets in PR #85 are passed, so the problem is resolved.
